### ISSUE TITLE
Question: Building Message inside of package that uses the message

### ISSUE THREAD

**Issue by firesurfer** [ament/ament_tools#85]
Is it possible to define and build a message in a package that has some more code that uses the message?
Or is it intended by design to separate messages and code? In the specific scenario I wanted to create a simple logger as a replacement until there is a ros2 logging package. It would be nicer if I could ship messages and logging code inside the same package.

**Comment by dirk-thomas** [comment]
Yes, as with ROS 1 you can put both in a package, messages as well as code.

The recommendation to keep messages in separate packages is simply that commonly separating the data format from the logic creating / consuming the data makes sense.

**Comment by jacquelinekay** [comment]
You should definitely be able to do this. Many of our existing examples do not do it because the common message definitions are re-used across many packages that do not share code, but do share message definitions. But it's not due to a limitation of the build system.

test_rclcpp and test_communication make message definitions used in the executables built by the package:

https://github.com/ros2/system_tests/tree/master/test_rclcpp
https://github.com/ros2/system_tests/tree/master/test_communication

**Comment by firesurfer** [comment]
I have the problem that the compiler can't find the headerfiles in the first run. 
I tried adding this (which didn't help):
```
include_directories(
		${CMAKE_BINARY_DIR}/rosidl_generator_cpp)
```
On the second run (without deleting the build directory) everthing compiles fine

**Comment by dirk-thomas** [comment]
Since it only compiles after repeated runs you are likely lacking a necessary target dependency. For the generation step you have specified a target name (the first argument of `rosidl_generate_interfaces`). Whatever library or executable you build which needs the generated headers must specify a target dependency on targe that.
